### ISSUE TITLE
Is this support Laravel 5.3?

### ISSUE THREAD

**Issue by aneeshsudhakaran** [jeroennoten/laravel-ckeditor#1]
I getting this error message, when try on Laravel 5.3
"Installation failed, reverting ./composer.json to its original content."

**Comment by jeroennoten** [comment]
Laravel 5.3 is supported, but probably there some conflicting dependencies. Could you show me the contents of your `composer.json`?

**Comment by aneeshsudhakaran** [comment]
Problem 1
    - jeroennoten/laravel-ckeditor v3.7.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.7.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.6.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.5.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.4.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.4.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.3.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.2.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.1.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.1.0 requires laravel/framework 5.1.*|5.2.* -> satisfiable by laravel/framework[5.1.x-dev, 5.2.41, 5.2.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - Installation request for jeroennoten/laravel-ckeditor ^3.1 -> satisfiable by jeroennoten/laravel-ckeditor[v3.1.0, v3.1.1, v3.2.0, v3.3.0, v3.4.0, v3.4.1, v3.5.0, v3.6.0, v3.7.0, v3.7.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by aneeshsudhakaran** [comment]
Problem 1
    - jeroennoten/laravel-ckeditor v3.7.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.7.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.6.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.5.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.4.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.4.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.3.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.2.0 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.1.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - jeroennoten/laravel-ckeditor v3.1.0 requires laravel/framework 5.1._|5.2._ -> satisfiable by laravel/framework[5.1.x-dev, 5.2.41, 5.2.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - Installation request for jeroennoten/laravel-ckeditor ^3.1 -> satisfiable by jeroennoten/laravel-ckeditor[v3.1.0, v3.1.1, v3.2.0, v3.3.0, v3.4.0, v3.4.1, v3.5.0, v3.6.0, v3.7.0, v3.7.1].

Installation failed, reverting ./composer.json to its original content.

May be my php version issue , right?

**Comment by jeroennoten** [comment]
The latest versions of this package require PHP 7.

**Comment by aneeshsudhakaran** [comment]
Ok Thank you

**Comment by jeroennoten** [comment]
Just want to let you know that PHP 7 is no longer a requirement for this package.

**Comment by Mohammed-akeel97** [comment]
y
