### ISSUE TITLE
PHP7 required?

### ISSUE THREAD

**Issue by Langdi** [jeroennoten/laravel-ckeditor#2]
Composer says this package requires a minimum php version of PHP7. However, I checked with PHP CompatInfo and it says it only needs PHP 5.4. Is there actually any code that requires PHP7?

**Comment by showFocus** [comment]
This command: php artisan vendor:publish --provider="JeroenNoten\LaravelCkEditor\ServiceProvider" --tag=assets

Results in: Nothing to publish for tag [assets].

**Comment by jeroennoten** [comment]
I think you're right. I removed the PHP 7 requirement. Can you let me know whether this works for you?

**Comment by Langdi** [comment]
Will do as soon as I deploy my application to a testing server. I'm on PHP7 on my local machine as well, but was concerned because production machines probably are not.

**Comment by jeroennoten** [comment]
Thanks!
