### ISSUE TITLE
Nothing to publish for tag [assets].

### ISSUE THREAD

**Issue by showFocus** [jeroennoten/laravel-ckeditor#3]
This command: `php artisan vendor:publish --provider="JeroenNoten\LaravelCkEditor\ServiceProvider" --tag=assets`

Results in: Nothing to publish for tag [assets].

**Comment by jeroennoten** [comment]
I think I changed it at some point to `php artisan vendor:publish --tag=ckeditor-assets`. Can you let me know if that works for you? If so, I will update the readme as well.

**Comment by showFocus** [comment]
That worked, thank you.

**Comment by jeroennoten** [comment]
Thanks for your feedback, the readme is now updated.
