### ISSUE TITLE
Greek Characters

### ISSUE THREAD

**Issue by andyz1974** [jeroennoten/laravel-ckeditor#9]
When I use ck-editor in textarea in Laravel, greek text is stored with html entities like this: <p>&Kappa;&tau;ή&mu;&alpha;&tau;&alpha;</p>
I set it to false like this @ckeditor('textareaId', ['entities_greek'=>'false']), but nothing changed.
Is there anything I can do?

**Comment by jeroennoten** [comment]
Try `false` instead of `'false'` (so without quotes).
